[package]
name = "caboose"
version = "0.1.0"
edition = "2021"

[lib]
name = "caboose"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
caboose_index = { path = "../caboose_index" }
numpy = "0.17.2"
sprs = "0.11"
